### ISSUE TITLE
IOError: [Errno 2] No such file or directory: samba-4.5.1/wscript_configure

### ISSUE THREAD

**Issue by cwkcyd** [google/samba-documents-provider#30]
FATAL: Failed to find a statfs method

/Users/wangyancong/Downloads/samba-4.5.1/lib/util/wscript: error: Traceback (most recent call last):

  File "/Users/wangyancong/Downloads/samba-4.5.1/third_party/waf/wafadmin/Utils.py", line 669, in recurse

    exec(compile(txt, file_path, 'exec'), dc)

  File "/Users/wangyancong/Downloads/samba-4.5.1/third_party/waf/wafadmin/Utils.py", line 639, in recurse

    txt = readf(file_path, m='rU')

  File "/Users/wangyancong/Downloads/samba-4.5.1/third_party/waf/wafadmin/Utils.py", line 164, in readf

    f = open(fname, m)

[IOError: [Errno 2] No such file or directory: '/Users/wangyancong/Downloads/samba-4.5.1/wscript_configure']

**[https://groups.google.com/forum/#!topic/samba-documents-provider/BEat3wiV47U](url)**

**Comment by cwkcyd** [comment]
use Ubuntu to build success, but mac failed

**Comment by ttanxu** [comment]
Apologies. Updated the readme.

Should've added this before.
