### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol

### ISSUE THREAD

**Issue by samonkey-zouyingjun** [google/samba-documents-provider#52]
# 1.I want to run on andorid22，so I choosed ndk toolchain like that:
./make-standalone-toolchain.sh \
--arch=arm --platform=android-21

# 2.and then,Adaptation api and gradle like that:
compileSdkVersion 22
minSdkVersion 21
targetSdkVersion 22

# 3.the quesetion is that,when i run the build apk to andorid-22 has fatal as bellow. but run on andorid-23 successful. How do I deal with？

----------
FATAL EXCEPTION: main
                                                 Process: com.google.android.sambadocumentsprovider, PID: 5022
                                                 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "state_path" referenced by "libsmbregistry-samba4.so"...
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                     at java.lang.System.loadLibrary(System.java:988)
                                                     at com.google.android.sambadocumentsprovider.SambaConfiguration.<clinit>(SambaConfiguration.java:37)
                                                     at com.google.android.sambadocumentsprovider.SambaProviderApplication.initializeSambaConf(SambaProviderApplication.java:77)
                                                     at com.google.android.sambadocumentsprovider.SambaProviderApplication.initialize(SambaProviderApplication.java:61)
                                                     at com.google.android.sambadocumentsprovider.SambaProviderApplication.init(SambaProviderApplication.java:117)
                                                     at com.google.android.sambadocumentsprovider.provider.SambaDocumentsProvider.onCreate(SambaDocumentsProvider.java:150)
                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1697)
                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1672)
                                                     at android.provider.DocumentsProvider.attachInfo(DocumentsProvider.java:171)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5025)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4620)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4560)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5280)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by samonkey-zouyingjun** [comment]
I have solved this problem by using a lower version of ndk：`https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip`
